using System.Text.Json;
using Ajudante.Core;
using Ajudante.Core.Engine;
using Ajudante.Core.Interfaces;
using Ajudante.Nodes.Common;

namespace Ajudante.Nodes.Logic;

[NodeInfo(
    TypeId = "logic.chatMenuRouter",
    DisplayName = "Chat Menu Router",
    Category = NodeCategory.Logic,
    Description = "Routes numbered WhatsApp/chat menu replies into safe automation intents",
    Color = "#EAB308")]
public sealed class ChatMenuRouterNode : ILogicNode
{
    private Dictionary<string, object?> _properties = new(StringComparer.OrdinalIgnoreCase);

    public string Id { get; set; } = "";

    public NodeDefinition Definition => new()
    {
        TypeId = "logic.chatMenuRouter",
        DisplayName = "Chat Menu Router",
        Category = NodeCategory.Logic,
        Description = "Routes numbered WhatsApp/chat menu replies into safe automation intents",
        Color = "#EAB308",
        InputPorts = new List<PortDefinition> { new() { Id = "in", Name = "In", DataType = PortDataType.Flow } },
        OutputPorts = new List<PortDefinition>
        {
            new() { Id = "screenshot", Name = "Screenshot", DataType = PortDataType.Flow },
            new() { Id = "command", Name = "Command", DataType = PortDataType.Flow },
            new() { Id = "systemInfo", Name = "System Info", DataType = PortDataType.Flow },
            new() { Id = "listFlows", Name = "List Flows", DataType = PortDataType.Flow },
            new() { Id = "runFlow", Name = "Run Flow", DataType = PortDataType.Flow },
            new() { Id = "stop", Name = "Stop", DataType = PortDataType.Flow },
            new() { Id = "unknown", Name = "Unknown", DataType = PortDataType.Flow },
            new() { Id = "intent", Name = "Intent", DataType = PortDataType.String },
            new() { Id = "commandText", Name = "Command", DataType = PortDataType.String },
            new() { Id = "flowId", Name = "Flow ID", DataType = PortDataType.String },
            new() { Id = "reason", Name = "Reason", DataType = PortDataType.String }
        },
        Properties = new List<PropertyDefinition>
        {
            new() { Id = "message", Name = "Message", Type = PropertyType.String, DefaultValue = "{{lastChatMessage}}", Description = "Incoming chat text. Supports {{variable}} templates." },
            new() { Id = "allowedCommands", Name = "Allowed Commands", Type = PropertyType.String, DefaultValue = "ipconfig,whoami,hostname,systeminfo,ver", Description = "Comma or line separated command allowlist." },
            new() { Id = "flowMenuStartNumber", Name = "Flow Menu Start Number", Type = PropertyType.Integer, DefaultValue = 10, Description = "First number reserved for runnable flows." },
            new() { Id = "flowCatalogJson", Name = "Flow Catalog JSON", Type = PropertyType.String, DefaultValue = "{{runnableFlowsCatalog}}", Description = "Catalog generated by List Runnable Flows." },
            new() { Id = "storeIntentInVariable", Name = "Store Intent In Variable", Type = PropertyType.String, DefaultValue = "chatIntent", Description = "Variable that receives the detected intent." },
            new() { Id = "storeCommandInVariable", Name = "Store Command In Variable", Type = PropertyType.String, DefaultValue = "requestedCommand", Description = "Variable that receives the safe command text." },
            new() { Id = "storeFlowIdInVariable", Name = "Store Flow ID In Variable", Type = PropertyType.String, DefaultValue = "requestedFlowId", Description = "Variable that receives the selected flow id." },
            new() { Id = "storeReasonInVariable", Name = "Store Reason In Variable", Type = PropertyType.String, DefaultValue = "chatRouteReason", Description = "Variable that receives a route reason for user feedback." }
        }
    };

    public void Configure(Dictionary<string, object?> properties)
    {
        _properties = new Dictionary<string, object?>(properties, StringComparer.OrdinalIgnoreCase);
    }

    public Task<NodeResult> ExecuteAsync(FlowExecutionContext context, CancellationToken ct)
    {
        var message = NodeValueHelper.ResolveTemplateProperty(context, _properties, "message", "").Trim();
        var allowedCommands = ParseList(NodeValueHelper.ResolveTemplateProperty(context, _properties, "allowedCommands", ""));
        var startNumber = Math.Max(1, NodeValueHelper.GetInt(_properties, "flowMenuStartNumber", 10));
        var catalogJson = NodeValueHelper.ResolveTemplateProperty(context, _properties, "flowCatalogJson", "");

        var route = ResolveRoute(message, allowedCommands, startNumber, catalogJson);
        Store(context, route);

        return Task.FromResult(NodeResult.Ok(route.OutputPort, new Dictionary<string, object?>
        {
            ["intent"] = route.Intent,
            ["commandText"] = route.CommandText,
            ["flowId"] = route.FlowId,
            ["flowNumber"] = route.FlowNumber,
            ["reason"] = route.Reason
        }));
    }

    private static RouteResult ResolveRoute(string message, IReadOnlySet<string> allowedCommands, int startNumber, string catalogJson)
    {
        if (string.IsNullOrWhiteSpace(message))
            return Unknown("emptyMessage", "Envie um numero do menu.");

        var firstToken = message.Split(' ', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? "";

        if (string.Equals(firstToken, "0", StringComparison.OrdinalIgnoreCase))
            return new RouteResult("stop", "stop", "", "", null, "stopRequested");

        if (string.Equals(firstToken, "1", StringComparison.OrdinalIgnoreCase))
            return new RouteResult("screenshot", "screenshot", "", "", null, "screenshotRequested");

        if (string.Equals(firstToken, "3", StringComparison.OrdinalIgnoreCase))
            return new RouteResult("systemInfo", "systemInfo", "", "", null, "systemInfoRequested");

        if (string.Equals(firstToken, "4", StringComparison.OrdinalIgnoreCase))
            return new RouteResult("listFlows", "listFlows", "", "", null, "listFlowsRequested");

        if (string.Equals(firstToken, "2", StringComparison.OrdinalIgnoreCase))
        {
            var command = message.Length > firstToken.Length
                ? message[firstToken.Length..].Trim()
                : "";
            if (string.IsNullOrWhiteSpace(command))
                return Unknown("missingCommand", "Informe o comando apos o numero 2.");

            var executable = command.Split(' ', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? "";
            if (!allowedCommands.Contains(executable))
                return Unknown("commandNotAllowed", $"Comando nao permitido: {executable}");

            return new RouteResult("command", "command", command, "", null, "commandAllowed");
        }

        if (int.TryParse(firstToken, out var flowNumber) && flowNumber >= startNumber)
        {
            var catalog = ParseCatalog(catalogJson);
            var selected = catalog.FirstOrDefault(item => item.Number == flowNumber);
            if (selected != null && !string.IsNullOrWhiteSpace(selected.FlowId))
                return new RouteResult("runFlow", "runFlow", "", selected.FlowId, flowNumber, "flowSelected");

            return Unknown("flowNotFound", $"Nao encontrei flow no menu com o numero {flowNumber}.");
        }

        return Unknown("unknownCommand", "Nao entendi esse comando.");
    }

    private void Store(FlowExecutionContext context, RouteResult route)
    {
        NodeValueHelper.SetVariableIfRequested(context, NodeValueHelper.GetString(_properties, "storeIntentInVariable", "chatIntent"), route.Intent);
        NodeValueHelper.SetVariableIfRequested(context, NodeValueHelper.GetString(_properties, "storeCommandInVariable", "requestedCommand"), route.CommandText);
        NodeValueHelper.SetVariableIfRequested(context, NodeValueHelper.GetString(_properties, "storeFlowIdInVariable", "requestedFlowId"), route.FlowId);
        NodeValueHelper.SetVariableIfRequested(context, NodeValueHelper.GetString(_properties, "storeReasonInVariable", "chatRouteReason"), route.Reason);
    }

    private static RouteResult Unknown(string reason, string message)
    {
        return new RouteResult("unknown", "unknown", "", "", null, $"{reason}: {message}");
    }

    private static IReadOnlySet<string> ParseList(string value)
    {
        var items = value.Split(new[] { ',', ';', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Select(item => item.Split(' ', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? "")
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        return items.Count > 0
            ? items
            : new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    }

    private static IReadOnlyList<FlowMenuItem> ParseCatalog(string catalogJson)
    {
        if (string.IsNullOrWhiteSpace(catalogJson) || catalogJson.Contains("{{", StringComparison.Ordinal))
            return Array.Empty<FlowMenuItem>();

        try
        {
            return JsonSerializer.Deserialize<FlowMenuItem[]>(catalogJson, JsonOptions) ?? Array.Empty<FlowMenuItem>();
        }
        catch (JsonException)
        {
            return Array.Empty<FlowMenuItem>();
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    private sealed record RouteResult(
        string OutputPort,
        string Intent,
        string CommandText,
        string FlowId,
        int? FlowNumber,
        string Reason);

    private sealed class FlowMenuItem
    {
        public int Number { get; set; }
        public string FlowId { get; set; } = "";
        public string Name { get; set; } = "";
    }
}
